### ISSUE TITLE
Automatically create the GitHub Release via GitHub Actions

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/create-rwjblue-release-it-setup#167]
Instead of creating the release locally (during release-it's pipeline), we should create a `.github/workflows/release.yml` that _effectively_ does:

```yml
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
```

This helps reduce the extra setup requirements (having a `$GITHUB_AUTH`).
